name: Add Github User to reward allowlist on PR Merge

on:
  push:
    branches:
      - main
      - master

jobs:
  reward:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: GH action to reward a contribution
        uses: ton-society/github-contribution-reward@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          x_api_key: ${{ secrets.X_API_KEY }}
          x_partner_id: ${{ secrets.X_PARTNER_ID }}
