name: Reward All Merged PRs

on:
  workflow_dispatch:
    inputs:
      per_page:
        description: 'Number of merged PRs to process'
        required: false
        default: '100'  # Default value shown in UI
        type: string

jobs:
  reward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ton-society/gh-ton-contribution-reward/.github/actions/rewards-for-merged-prs@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          x_api_key: ${{ secrets.X_API_KEY }}
          x_partner_id: ${{ secrets.X_PARTNER_ID }}
          activity_id: 5636
          per_page: ${{ inputs.per_page }}
